name: first workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: |
              echo "First input"
              echo "Second input"

  
      
        
      
